### ISSUE TITLE
RF 1 - Eu, como usuário, desejo Inserir parâmetros de configuração para determinada tinta

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#1]
# Eu, como usuário, desejo Inserir parâmetros de configuração para determinada tinta

- História de Usuário: 01
- Tipo: Funcional
- Prioridade: Should
- Sprint: 1
- Estimativa de esforço (em horas): 2,5

## Tasks

- [x] Criar modal com os seguintes inputs (tipo de tinta, quantidade de tintas, temperatura do flashcure, velocidade do motor)
- [x] Salvar os dados inseridos em um estado
- [x] Criar endpoints no backend para receber os parâmetros de tintas advindas do front-end
- [x] Conectar front-end e back-end

## Critérios de aceitação

- [x] O usuário deve ser capaz de inserir os parâmetros para uma determinada tinta
- [x] Ao preencher os parâmetros, esses dados devem ser salvos
- [x] Deve ser possível enviar os dados do front-end para o back-end
- [x] Interface de acordo com o protótipo

**Comment by fellipe-araujo** [comment]
## Issues semelhantes que foram feitas em conjunto

* #8 (história de usuário: 18);
* #2 (história de usuário: 02);
* #3 (história de usuário: 01).

**Comment by ErickGiffoni** [comment]
Show ! Obg pelas descrições nos comentários
