### ISSUE TITLE
RF 8 - Visualizar a velocidade configurada para o motor

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#12]
# Eu, como usuário/sistema, desejo

- Tipo: Funcional
- Prioridade: Must
- Sprint: 2
- Estimativa de esforço (em horas): 1 hora

## Tasks

- [x] Criar card para visualizar a velocidade do motor definida

## Critérios de aceitação

- [x] Deve ser possível visualizar a velocidade definida para o motor no dashboard do sistema
- [x] Deve ser possível visualizar as velocidades de limite do sistema
- [x] O card para visualização das velocidades deve estar de acordo com o protótipo
