### ISSUE TITLE
RF 17 - Receber um relatório da qualidade de impressão

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#15]
# Eu, como usuário, desejo receber um relatório de qualidade de impressão.

- Tipo: Funcional
- Prioridade: Must
- Sprint: 2
- Estimativa de esforço (em horas): 8

## Tasks

- [x] Criar uma página para visualizar o relatório da qualidade analisada;
- [x] Criar 2 dropdowns: um para selecionar a produção desejado e outro para o lote desejado;
- [x] Conectar com o back-end para mostrar os dados de forma dinâmica.

## Critérios de aceitação

- [x] Deve ser possível navegar para a página de Relatório de Qualidade;
- [x] Após o usuário selecionar os valores nos dropdowns, deve ser renderizado em tela o relatório com os dados dinâmicos.

**Comment by ErickGiffoni** [comment]
@thallysbraz como está o andamento ?
