### ISSUE TITLE
RF 20 - Analisar o formato da estampa

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#16]
## US 20 - Eu, como sistema, desejo analisar o formato da estampa

- Tipo: Funcional
- Prioridade: Should
- Sprint: 2
- Estimativa de esforço (em horas): 4

## Tasks

- [x] No front-end, deve ser possível enviar ou tirar uma foto para esta ser utilizada como referência;
- [x] Cortar a estampa para uma melhor análise;
- [x] Realizar a análise do formato entre a imagem de referência e a imagem tirada do lote;
- [x] Retornar a similaridade entre as imagens (valor de 0 a 1).

## Critérios de aceitação

- [x] O usuário deve conseguir enviar/tirar uma foto no momento da criação de uma produção;
- [x] Deve ser possível realizar o corte da estampa de forma automática;
- [x] Após a foto ser tirada e ter sido realizada a análise, deve ser retornado a similaridade entre as imagens.
