### ISSUE TITLE
RF 22 - Analisar erros de impressão em decorrência de falhas na matriz

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#17]
# Eu, como sistema, desejo analisar os erros de impressão em decorrer da matriz

- Tipo: Funcional
- Prioridade: Must
- Sprint: 2
- Estimativa de esforço (em horas): 2

## Tasks

- [x] No front-end, deve ser possível enviar ou tirar uma foto para esta ser utilizada como referência;
- [x] Cortar a estampa para uma melhor análise;
- [x] Realizar a análise de falhas no decorrer da matriz;
- [x] Retornar a quantidade de falhas encontradas.

## Critérios de aceitação

- [x] O usuário deve conseguir enviar/tirar uma foto no momento da criação de uma produção;
- [x] Deve ser possível realizar o corte da estampa de forma automática;
- [x] Após a foto ser tirada e ter sido realizada a análise, deve ser retornado a quantidade de falhas encontradas.
