### ISSUE TITLE
RF 23 - Executar produção

### ISSUE THREAD

**Issue by SamButers** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#20]
# Eu, como sistema, desejo Executar uma produção

- Tipo: Funcional
- Prioridade: Must
- Sprint: 3
- Estimativa de esforço (em horas): 6

## Tasks
- [x] O sistema deve manter o estado do sistema
- [x] O sistema deve manipular o estado e periféricos de acordo com input do usuário
- [x] O sistema deve permitir que a interface obtenha o seu estado

## Critérios de aceitação

- [x] A endpoint /controleProducao acessa a última produção criada
