### ISSUE TITLE
RNF 13 - Permitir conexão remota

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#22]
# Eu, como sistema, desejo permitir conexão remota

- Tipo: Não-Funcional
- Prioridade: should
- Sprint: 3
- Estimativa de esforço (em horas): 5

## Tasks

- [x] Habilitar a raspberry para atuar como hotspot (access point)
- [x] Criar script para desabilitar o hotspot
- [x] Configurar o boot da rasp para inicializar o back e o front
- [x] Configurar o boot para abrir o navegador na interface do front - feito em /etc/xdg/lxsession/LXDE-pi/autostart

## Critérios de aceitação

- [x] Ser capaz de habilitar/desabilitar o hotspot por meio das instruções via script shell
- [x] Boot configurado para iniciar o back
- [x] Boot configurado para iniciar o front
- [x] Boot configurado para abrir o navegador na interface do front

**Comment by ErickGiffoni** [comment]
Horas já dedicadas: ~2
Configurei o boot para iniciar o back e o front, porém está dando erro.
Logo logo terminarei

**Comment by ErickGiffoni** [comment]
Feito !
