### ISSUE TITLE
RF 16 - Ligar e desligar o sistema

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#26]
# Eu, como usuário, desejo ligar e desligar o sistema

- Tipo: Funcional
- Prioridade: Could
- Sprint: 4
- Estimativa de esforço (em horas): 6

## Detalhes

**Ligar**: enviar comandos para ligar os periféricos eletrônicos, como flashcure e câmera. Pro caso do motor, permitir que ele gire.

**Desligar**: enviar comandos para os periféricos eletrônicos (flashcure, câmera) serem desligados, ou seja, as luzes do Flashcure iriam apagar, a câmera iria desligar. O motor ficará “bloqueado” de qualquer ação que queira fazer ele girar.
Isso tudo o sistema ainda estaria alimentado, porém “desligado”.

**Adicional**: dado um certo tempo de inatividade do usuário com o software, porque ele desligou os periféricos, por exemplo, o sistema poderia colocar a Rasp num modo de low power, conservação de energia.

## Tasks

- [ ] implementar o botão de ligar
- [ ] implementar o botão de desligar
- [ ] fazer o endpoint de ligar
- [ ] fazer o endpoint de desligar
- [ ] colocar a Rasp em conservação de energia caso haja muito tempo (5 minutos) de inatividade

## Critérios de aceitação

- [ ] Caso uma produção esteja em andamento e o usuário clique em "desligar", o sistema deve automaticamente pausar a produção (fazer essa verificação no frontend)
- [ ] Botão de ligar na cor verde
- [ ] Botão de desligar na cor vermelha
- [ ] endpoint de ligar feito
- [ ] endpoint de desligar feito
